"""
Debug script to see what signals are being generated by the Liquid Momentum strategy.
"""

from __future__ import annotations

import sys
from pathlib import Path
from datetime import date, datetime, timedelta

# Add the backend directory to the path
ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.app.config.settings import Settings
from backend.app.data.mock_alpaca import MockAlpacaClient
from backend.app.data.market_data import MarketDataService
from backend.app.strategies.liquid_momentum import LiquidMomentumStrategy
from backend.app.features.engine import momentum, last_close


class DebugMockAlpacaClient(MockAlpacaClient):
    """
    Mock client that allows us to inspect internal state.
    """

    def __init__(self, initial_price: float = 450.0):
        super().__init__()
        self._spy_price = initial_price
        self._qqq_price = initial_price * 0.85
        self._iwm_price = initial_price * 0.5
        self._price_history = {
            "SPY": [initial_price],
            "QQQ": [self._qqq_price],
            "IWM": [self._iwm_price]
        }
        self._day = 0
        self._volatility = 0.015

    def get_bars(self, symbol: str, *, days: int = 30) -> list:
        """
        Return historical bar data and also return the price changes for debugging.
        """
        from backend.app.data.models import Bar

        price_changes = []
        while len(self._price_history[symbol]) < days:
            last_price = self._price_history[symbol][-1]

            if symbol == "SPY":
                trend = 0.0002
            elif symbol == "QQQ":
                trend = 0.0003
            else:  # IWM
                trend = 0.0001

            mean_reversion = -0.05 * (self._price_history[symbol][-1] -
                                    sum(self._price_history[symbol][-10:])/min(len(self._price_history[symbol]), 10)) if len(self._price_history[symbol]) >= 10 else 0

            change = trend + mean_reversion + (self._volatility * (0.5 - (hash(f"{last_price}{len(self._price_history[symbol])}") % 1000) / 500.0))
            price_changes.append(change)
            new_price = last_price * (1 + change)
            self._price_history[symbol].append(new_price)

        start_idx = max(0, len(self._price_history[symbol]) - days)
        price_slice = self._price_history[symbol][start_idx:]
        changes_slice = price_changes[start_idx:] if price_changes else [0.0] * len(price_slice)

        bars = []
        base_time = datetime.now() - timedelta(days=len(price_slice))

        for i, (price, change) in enumerate(zip(price_slice, changes_slice)):
            intraday_vol = abs(change) * 2 + 0.003 if i > 0 else 0.01

            high = price * (1 + abs(intraday_vol * 0.5))
            low = price * (1 - abs(intraday_vol * 0.5))
            open_price = price_slice[i-1] * (1 + intraday_vol * 0.3) if i > 0 else price

            high = max(high, open_price, price)
            low = min(low, open_price, price)

            bar = Bar(
                symbol=symbol,
                timestamp=base_time + timedelta(days=i),
                open=open_price,
                high=high,
                low=low,
                close=price,
                volume=50_000_000 + (i * 100000)
            )
            bars.append(bar)

        # Also return the price changes for analysis
        self.last_price_changes = changes_slice
        return bars


def debug_strategy_signals():
    """Debug what signals the strategy is generating."""
    print("=== Debugging Liquid Momentum Strategy Signals ===\n")

    # Use a short date range for debugging
    end_date = date.today()
    start_date = end_date - timedelta(days=30)

    print(f"Debug Period: {start_date} to {end_date}")
    print(f"Total Days: {(end_date - start_date).days}\n")

    # Settings
    settings = Settings(
        underlyings="SPY,QQQ,IWM",
        max_bid_ask_spread=0.25,
        min_open_interest=0,
        min_option_volume=0,
        min_dte=0,
        max_dte=365,
        max_risk_per_trade=0.02,
        max_portfolio_exposure=0.3,
        max_positions=5,
        max_underlying_concentration=0.2,
        trading_enabled=True,
    )

    # Create debug market data service
    client = DebugMockAlpacaClient(initial_price=450.0)
    market_data = MarketDataService(client)

    # Create strategy
    strategy = LiquidMomentumStrategy(market_data, settings)

    print(f"Strategy threshold: {strategy.threshold}")
    print(f"Settings underlyings: {settings.underlyings}\n")

    # Analyze each symbol
    for symbol in ["SPY", "QQQ", "IWM"]:
        print(f"--- Analyzing {symbol} ---")

        # Get bars
        bars = market_data.bars(symbol, days=20)
        print(f"Number of bars: {len(bars)}")

        if len(bars) >= 5:
            # Calculate momentum
            mom = momentum(bars, lookback=5)
            close = last_close(bars)

            print(f"5-day momentum: {mom:.4f} ({mom:.2%})")
            print(f"Last close: {close:.2f}")

            # Show recent price changes
            if hasattr(client, 'last_price_changes') and len(client.last_price_changes) >= 5:
                print(f"Last 5 daily changes: {[f'{c:.2%}' for c in client.last_price_changes[-5:]]}")

            # Check if signal would be generated
            if mom is not None and close is not None:
                if abs(mom) < strategy.threshold:
                    print(f"MOMENTUM BELOW THRESHOLD ({strategy.threshold:.3f}) - NO SIGNAL")
                else:
                    direction = "long" if mom > 0 else "short"
                    print(f"MOMENTUM ABOVE THRESHOLD - {direction.upper()} SIGNAL POSSIBLE")

                    # Show what the signal would look like
                    quote = market_data.quote(symbol)
                    price = quote.mid or quote.last or close
                    print(f"Current price: {price:.2f}")

                    # Get option chain
                    right = "call" if direction == "long" else "put"
                    chain = market_data.option_chain(
                        symbol,
                        min_dte=settings.min_dte,
                        max_dte=settings.max_dte,
                        right=right,
                        limit=10,
                    )

                    if chain:
                        print(f"Found {len(chain)} {right} contracts")
                        # Show first few
                        for i, contract in enumerate(chain[:3]):
                            snap = market_data.option_snapshot(contract.symbol, underlying_price=price)
                            if snap and snap.quote and snap.quote.mid:
                                dist = abs(contract.strike - price) / price
                                spread = snap.quote.spread_pct
                                oi = contract.open_interest
                                print(f"  {i+1}. {contract.symbol}: strike={contract.strike:.2f}, "
                                      f"exp={contract.expiration}, dist={dist:.2%}, "
                                      f"spread={spread:.2% if spread else 'N/A'}, "
                                      f"OI={oi if oi else 'N/A'}, price={snap.quote.mid:.2f}")
                    else:
                        print("No option chain found")
            else:
                print("MOMENTUM OR CLOSE IS NONE")
        else:
            print("NOT ENOUGH BARS FOR MOMENTUM CALCULATION")

        print()

    # Now test actual signal generation
    print("--- Testing Actual Signal Generation ---")

    # Create market state
    bars_spy = market_data.bars("SPY", days=20)
    bars_qqq = market_data.bars("QQQ", days=20)
    bars_iwm = market_data.bars("IWM", days=20)

    market_state = {
        "underlyings": ["SPY", "QQQ", "IWM"],
        "bars_data": {
            "SPY": bars_spy,
            "QQQ": bars_qqq,
            "IWM": bars_iwm
        }
    }

    # Generate signals
    signals = strategy.generate_signals(market_state)

    print(f"Number of signals generated: {len(signals)}")

    for i, signal in enumerate(signals):
        print(f"\nSignal {i+1}:")
        print(f"  Underlying: {signal.underlying}")
        print(f"  Direction: {signal.direction}")
        print(f"  Confidence: {signal.confidence:.2f}")
        print(f"  Thesis: {signal.thesis}")
        print(f"  Expected Edge: {signal.expected_edge:.4f}")
        print(f"  Contract: {signal.contract}")
        if signal.snapshot:
            print(f"  Snapshot: {signal.snapshot.underlying} {signal.snapshot.contract.right} "
                  f"{signal.snapshot.contract.strike} exp {signal.snapshot.contract.expiration}")
            if signal.snapshot.quote:
                print(f"  Quote: bid={signal.snapshot.quote.bid:.2f}, ask={signal.snapshot.quote.ask:.2f}, "
                      f"mid={signal.snapshot.quote.mid:.2f}, last={signal.snapshot.quote.last:.2f}")


if __name__ == "__main__":
    debug_strategy_signals()